version: '3.8'

services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: datalake
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped

volumes:
  database_data:
